Repository semiotic-ai/timeline-aggregation-protocol, pull requests merged in 2023-08, with the labels that each got.

#164 refactor!: Replace "collateral" with "escrow"
  tap_core/src/adapters/escrow_adapter.rs
  tap_core/src/adapters/mod.rs
  tap_core/src/adapters/test/collateral_adapter_mock.rs
  tap_core/src/adapters/test/escrow_adapter_mock.rs
  tap_core/src/adapters/test/escrow_adapter_test.rs
  tap_core/src/adapters/test/mod.rs
  tap_core/src/tap_manager/manager.rs
  tap_core/src/tap_manager/test/manager_test.rs
  tap_core/src/tap_receipt/mod.rs
  tap_core/src/tap_receipt/receipt_auditor.rs
  tap_core/src/tap_receipt/received_receipt.rs
  tap_core/src/tap_receipt/tests/received_receipt_tests.rs
  tap_integration_tests/tests/indexer_mock/mod.rs
  tap_integration_tests/tests/showcase.rs
Labels: refactor

#165 refactor(core)!: make ChecksAdapter return Result
  tap_core/src/adapters/receipt_checks_adapter.rs
  tap_core/src/adapters/test/receipt_checks_adapter_mock.rs
  tap_core/src/adapters/test/receipt_checks_adapter_test.rs
  tap_core/src/tap_receipt/receipt_auditor.rs
Labels: refactor

#167 162 eip712 domain separator info should be set by user
  tap_aggregator/Cargo.toml
  tap_aggregator/src/aggregator.rs
  tap_aggregator/src/main.rs
  tap_aggregator/src/server.rs
  tap_core/Cargo.toml
  tap_core/benches/timeline_aggretion_protocol_benchmark.rs
  tap_core/src/adapters/escrow_adapter.rs
  tap_core/src/adapters/receipt_checks_adapter.rs
  tap_core/src/adapters/test/escrow_adapter_mock.rs
  tap_core/src/adapters/test/escrow_adapter_test.rs
  tap_core/src/adapters/test/rav_storage_adapter_test.rs
  tap_core/src/adapters/test/receipt_checks_adapter_mock.rs
  tap_core/src/adapters/test/receipt_checks_adapter_test.rs
  tap_core/src/adapters/test/receipt_storage_adapter_test.rs
  tap_core/src/eip_712_signed_message.rs
  tap_core/src/error.rs
  tap_core/src/lib.rs
  tap_core/src/receipt_aggregate_voucher.rs
  tap_core/src/tap_manager/manager.rs
  tap_core/src/tap_manager/test/manager_test.rs
  tap_core/src/tap_receipt/mod.rs
  tap_core/src/tap_receipt/receipt.rs
  tap_core/src/tap_receipt/receipt_auditor.rs
  tap_core/src/tap_receipt/tests/receipt_tests.rs
  tap_core/src/tap_receipt/tests/received_receipt_tests.rs
  tap_integration_tests/Cargo.toml
  tap_integration_tests/tests/indexer_mock/mod.rs
  tap_integration_tests/tests/showcase.rs
Labels: enhancement

#169 feat(tap-aggregator): allow argument for key derive path to be used w…
  tap_aggregator/src/main.rs
Labels: enhancement

#172 fix(core): Update alloy to v0.3.2
  tap_aggregator/Cargo.toml
Labels: bug

#174 fix: Update alloy to v0.3.2
  tap_core/Cargo.toml
  tap_integration_tests/Cargo.toml
Labels: bug

#171 ci: improve rust cache
  .github/workflows/tests.yml
Labels: CI
