Repository semiotic-ai/timeline-aggregation-protocol, pull requests merged in 2023-07, with the labels that each got.

#126 Improve CI
  .github/workflows/conventional_commits.yml
  .github/workflows/dco_check.yml
  .github/workflows/release_please.yml
  .github/workflows/tests.yml
Labels: CI

#128 feat(receipt_storage_adapter): Use RangeBounds
  tap_core/src/adapters/receipt_storage_adapter.rs
  tap_core/src/adapters/test/receipt_storage_adapter_mock.rs
Labels: enhancement, refactor

#127 Fix: Receipts w/ consecutive timestamps failed
  tap_core/src/tap_manager/manager.rs
  tap_core/src/tap_manager/test/manager_test.rs
  tap_core/src/tap_receipt/receipt_auditor.rs
Labels: bug

#131 refactor(receipt_storage_adapter)!: prune trait
  tap_core/src/adapters/receipt_storage_adapter.rs
  tap_core/src/adapters/test/receipt_storage_adapter_mock.rs
Labels: refactor

#132 Add document to RAV storage adapter, adapter mod, tap_manager mod
  tap_core/src/adapters/mod.rs
  tap_core/src/adapters/rav_storage_adapter.rs
  tap_core/src/adapters/test/rav_storage_adapter_mock.rs
  tap_core/src/tap_manager/mod.rs
Labels: documentation

#130 feat(manager): add receipts_auto_delete
  tap_core/src/tap_manager/manager.rs
  tap_core/src/tap_manager/test/manager_test.rs
Labels: enhancement

#136 ci: test doc's code snippets
  .github/workflows/tests.yml
Labels: CI

#137 fix(aggregator): short args removed
  tap_aggregator/src/main.rs
Labels: bug

#138 docs(aggregator): add various ops tips
  tap_aggregator/README.md
Labels: documentation, Security

#147 docs(adapters): adds docs to receipt storage adapter
  tap_core/src/adapters/receipt_storage_adapter.rs
Labels: documentation

#153 chore: cleanup tap_core deps
  tap_core/Cargo.toml
Labels: Security, dependency, refactor

#150 docs(adapters): adds docs to collateral adapter
  tap_core/src/adapters/collateral_adapter.rs
Labels: documentation

#152 feat(aggregator): add prometheus metrics
  tap_aggregator/Cargo.toml
  tap_aggregator/src/lib.rs
  tap_aggregator/src/main.rs
  tap_aggregator/src/metrics.rs
  tap_aggregator/src/server.rs
  tap_integration_tests/Cargo.toml
Labels: enhancement

#155 ci: fix clippy
  .github/workflows/tests.yml
  tap_aggregator/src/aggregator.rs
  tap_aggregator/src/main.rs
  tap_core/src/adapters/test/receipt_checks_adapter_test.rs
  tap_core/src/tap_manager/test/manager_test.rs
  tap_integration_tests/clippy.toml
  tap_integration_tests/tests/indexer_mock/mod.rs
  tap_integration_tests/tests/showcase.rs
Labels: CI, refactor

#157 docs(adapter): adds docs to receipt checks adapter
  tap_core/src/adapters/receipt_checks_adapter.rs
Labels: documentation

#159 feat: serde for ReceivedReceipt
  tap_core/src/tap_receipt/mod.rs
  tap_core/src/tap_receipt/received_receipt.rs
Labels: Needed feature

#161 refactor!(core): make it all async
  tap_core/Cargo.toml
  tap_core/benches/timeline_aggretion_protocol_benchmark.rs
  tap_core/src/adapters/collateral_adapter.rs
  tap_core/src/adapters/rav_storage_adapter.rs
  tap_core/src/adapters/receipt_checks_adapter.rs
  tap_core/src/adapters/receipt_storage_adapter.rs
  tap_core/src/adapters/test/collateral_adapter_mock.rs
  tap_core/src/adapters/test/collateral_adapter_test.rs
  tap_core/src/adapters/test/rav_storage_adapter_mock.rs
  tap_core/src/adapters/test/rav_storage_adapter_test.rs
  tap_core/src/adapters/test/receipt_checks_adapter_mock.rs
  tap_core/src/adapters/test/receipt_checks_adapter_test.rs
  tap_core/src/adapters/test/receipt_storage_adapter_mock.rs
  tap_core/src/adapters/test/receipt_storage_adapter_test.rs
  tap_core/src/lib.rs
  tap_core/src/tap_manager/manager.rs
  tap_core/src/tap_manager/test/manager_test.rs
  tap_core/src/tap_receipt/receipt_auditor.rs
  tap_core/src/tap_receipt/received_receipt.rs
  tap_core/src/tap_receipt/tests/received_receipt_tests.rs
  tap_integration_tests/tests/indexer_mock/mod.rs
  tap_integration_tests/tests/showcase.rs
Labels: Needed feature
