Repository semiotic-ai/timeline-aggregation-protocol, pull requests merged in 2023-06, with the labels that each got.

#96 feat(aggregator): basic JSON-RPC API version mgmt
  tap_aggregator/Cargo.toml
  tap_aggregator/README.md
  tap_aggregator/src/api_versioning.rs
  tap_aggregator/src/error_codes.rs
  tap_aggregator/src/jsonrpsee_helpers.rs
  tap_aggregator/src/main.rs
  tap_aggregator/src/server.rs
Labels: Needed feature

#100 ci: Adding release-please
  .github/workflows/release_please.yml
  .release-please-manifest.json
  release-please-config.json
  tap_aggregator/Cargo.toml
  tap_core/Cargo.toml
Labels: CI

#101 Showcase test
  Cargo.toml
  tap_aggregator/src/lib.rs
  tap_aggregator/src/main.rs
  tap_integration_tests/Cargo.toml
  tap_integration_tests/tests/indexer_mock/mod.rs
  tap_integration_tests/tests/lib.rs
  tap_integration_tests/tests/showcase.rs
Labels: Needed feature

#111 Recommended max receipts per aggregate
  tap_aggregator/README.md
  tap_aggregator/src/server.rs
Labels: documentation

#116 Fix aggregator timestamp check
  tap_aggregator/src/aggregator.rs
Labels: bug, Security
